### ISSUE TITLE
Clarify where user should put `wg0.conf`

### ISSUE THREAD

**Issue by soredake** [hotio/base#23]
Thank you for your images that include vpn support out of the box, but, after reading this:
![image](https://github.com/hotio/base/assets/5204968/c126003b-7759-40f9-8318-06d3f481f11e)

I don't really understand *where* I should put `wg0.conf`.

**Comment by mrhotio** [comment]
<img width="802" alt="Scherm­afbeelding 2024-04-02 om 06 57 02" src="https://github.com/hotio/base/assets/26902309/4a95378e-764f-42c8-b324-6911dd2aab3f">
